version: '3.8'

services:
  ffc-demo-payment-web:
    command: npm run start:watch
    build:
      target: development
    image: ffc-demo-payment-web-zap-scan
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output:/home/node/test-output

  zap-baseline-scan:
    image: owasp/zap2docker-stable:2.14.0
    command: zap-baseline.py -t http://ffc-demo-payment-web:${PORT:-3000} -c config/zap.conf -r test-output/zap-report.html -a -d -I
    depends_on:
      - ffc-demo-payment-web
    volumes:
      - ./test-output:/zap/wrk/test-output
      - ./zap:/zap/wrk/config
