apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ffc-demo-payment-web"
  description: |
    Digital service mock to view scheduled payments for financial aid in the event a property subsides into mine shaft. This is the web front end for the application.
  annotations:
    github.com/project-slug: DEFRA/ffc-demo-payment-web
    dev.azure.com/project: DEFRA-FFC
    dev.azure.com/build-definition: ffc-demo-payment-web
    sonarqube.org/project-key: adp-ffc-demo-payment-web
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
  tags:
    - node
    - service-bus
    - redis
    - internal
    - front-end
  links:
    - url: https://github.com/DEFRA/ffc-demo-payment-web
      title: View repository
      icon: github
    - url: https://dev.azure.com/defragovuk/DEFRA-FFC/_build?definitionId=4965
      title: CI/CD Pipeline
    - url: https://sonarcloud.io/project/overview?id=adp-ffc-demo-payment-web
      title: SonarCloud Analysis
spec:
  type: frontend
  lifecycle: beta
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  consumesApis:
    - "api:default/fcp-payments-api"
    
