version: '3.7'

# This override file should be used when running tests in CI pipelines
# to run tests against app code from the Docker image without binding
# ports to the host machine.

services:
  ffc-demo-payment-web:
    build:
      target: development
    image: ffc-demo-payment-web-development
    command: npm test
    environment:
      NODE_ENV: test
      OIDC_PROVIDER: dev
      OKTA_DOMAIN: mydomain.otka.com
      OKTA_CLIENT_ID: placeholderclientid
      OKTA_CLIENT_SECRET: placeholdersecret
      OKTA_AUTH_SERVER_ID: placeholderauthserverid
      B2C_CLIENT_ID: b2cplaceholderclientid
      B2C_CLIENT_SECRET: b2cplaceholdersecret
      B2C_URL: b2cplaceholderauthserverid
    volumes:
      - ./app/:/home/node/app/
      - ./test/:/home/node/test/
      - ./jest.config.js:/home/node/jest.config.js
      - ./jest.setup.js:/home/node/jest.setup.js
      - ./package.json:/home/node/package.json
      - ./test-output/:/home/node/test-output/
