version: '3.8'

services:
  ffc-demo-payment-web:
    command: npm run start:watch
    build:
      target: development
    image: ffc-demo-payment-web-zap-scan
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output:/home/node/test-output

  zap-baseline-scan:
    image: softwaresecurityproject/zap-bare:2.14.0
    command: zap.sh -cmd -quickurl http://ffc-demo-payment-web:3000 -zapit http://ffc-demo-payment-web:3000 -configfile config/zap.conf -quickout test-output/zap-report.html -silent -quickprogress
    depends_on:
      - ffc-demo-payment-web
    volumes:
      - ./test-output:/zap/test-output
      - ./zap:/zap/config
