version: '3.7'

services:
  ffc-demo-payment-web:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY}
    image: ffc-demo-payment-web
    environment:
      NODE_ENV: development
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookiecookiecookiecookie
      OKTA_ENABLED: ${OKTA_ENABLED:-true}
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_AUTH_SERVER_ID: ${OKTA_AUTH_SERVER_ID}
      SITE_URL: http://localhost:3006
      PAYMENT_SERVICE_URL: http://ffc-demo-payment-service:3004
