version: '3.7'

services:
  ffc-demo-payment-web:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY}
    image: ffc-demo-payment-web
    environment:
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookiecookiecookiecookie
      OKTA_DOMAIN: ${OKTA_DOMAIN:-mydomain.otka.com}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID:-placeholder}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET:-placeholder}
      SITE_URL: http://localhost:3006
