version: '3.8'

services:
  ffc-demo-payment-web:
    build:
      context: .
      target: production
    image: ffc-demo-payment-web
    container_name: ffc-demo-payment-web
    environment:
      NODE_ENV: development
      APPINSIGHTS_CLOUDROLE: ffc-demo-payment-web-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookiecookiecookiecookie
      PAYMENT_SERVICE_URL: http://ffc-demo-payment-service:3004
      PACT_DO_NOT_TRACK: 1
      GOOGLE_TAG_MANAGER_KEY: GTM-N5QK7RL
