version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-demo-payment-web:
    build:
      target: development
    image: ffc-demo-payment-web
    ports:
      - "3006:3000"
      - "9234:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./jest.config.js:/home/node/jest.config.js
      - ./jest.setup.js:/home/node/jest.setup.js
      - ./package.json:/home/node/package.json
