namespace: ffc-demo
service:
  port: 443
  type: NodePort
container:
  allowPrivilegeEscalation: true
  imagePullPolicy: Always
ingress:
  endPoint: ffc-demo-payment-web
  server: ffc-dev.aws-int.defra.cloud
