environment: development
image: ffc-demo-payment-web
name: ffc-demo-payment-web
namespace: ffc-demo
workstream: ffc-demo

labels: {}

appInsights:
  connectionString:

service:
  port: 80
  type: ClusterIP

container:
  requestMemory: 20Mi
  requestCpu: 20m
  limitMemory: 100Mi
  limitCpu: 100m
  imagePullPolicy: IfNotPresent
  staticCacheTimeoutMillis: 54000
  restClientTimeoutMillis: 20000
  paymentServiceUrl: http://ffc-demo-payment-service.ffc-demo
  port: 3000
  cookiePassword: secret
  googleTagManagerKey: GTM-N5QK7RL

ingress:
  class: nginx
  endpoint: ffc-demo-payment
  server: example.com

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-demo
  roleArn: true

containerConfigMap:
  name: 'ffc-demo-payment-web-config-map'
  configServiceUrl: 'https://sndadpinfac1401.azconfig.io'
  auth:
    workloadIdentity:
      clientId: e9badf28-ce66-4dd3-97e1-e28bfb1da26b
  keyValues:
    labelFilter: 'ffc-demo-payment-web'
    refresh:
      interval: 2m
      monitorKey: 'Sentinel'
      monitorLabel: 'ffc-demo-payment-web'
    keyVaults:
      secretName: ffc-demo-payment-web-container-secret
      refresh:
        interval: 2m

managedIdPrefix: sndadpinfmid1401
userAssignedIdentity:
  managedIdName: ffc-demo-services