image: ffc-demo-payment-web
name: ffc-demo-payment-web
namespace: ffc-demo

labels: {}

container:
  memCpuTier: M
  port: 3000

ingress:
  class: nginx
  endpoint: ffc-demo-payment
  server: example.com

deployment:
  priorityClassName: low
  minReadySeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-demo
  roleArn: true