environment: development
image: ffc-demo-payment-web
name: ffc-demo-payment-web
namespace: ffc-demo
workstream: ffc-demo

labels: {}

appInsights:
  key:

containerConfigMap:
   name: ffc-demo-payment-web-config-map

containerSecret:
  name: ffc-demo-payment-web-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

container:
  requestMemory: 5Mi
  requestCpu: 5m
  limitMemory: 80Mi
  limitCpu: 80m
  imagePullPolicy: IfNotPresent
  staticCacheTimeoutMillis: 54000
  restClientTimeoutMillis: 20000
  paymentServiceUrl: http://ffc-demo-payment-service.ffc-demo
  port: 3000
  cookiePassword: secret
  googleTagManagerKey: GTM-N5QK7RL

ingress:
  class: nginx
  endpoint: ffc-demo-payment
  server: example.com

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:
  useLinkerd: true

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
