{{- define "ffc-demo-payment-web.container" -}}
ports:
- name: http
  containerPort: {{ .Values.container.port }}
  protocol: TCP
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4 }}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4 }}
{{- end -}}
