{{- define "ffc-demo-payment-web.container" -}}
env:
- name: NODE_ENV
  value: {{ quote .Values.environment }}
- name: PORT
  value: {{ quote .Values.container.port }}
- name: STATIC_CACHE_TIMEOUT_IN_MILLIS
  value: {{ quote .Values.container.staticCacheTimeoutMillis }}
- name: REST_CLIENT_TIMEOUT_IN_MILLIS
  value: {{ quote .Values.container.restClientTimeoutMillis }}
- name: PAYMENT_SERVICE_URL
  value: {{ quote .Values.container.paymentServiceUrl }}
- name: COOKIE_PASSWORD
  value: {{ quote .Values.container.cookiePassword }}
- name: OIDC_PROVIDER
  value: {{ quote .Values.oidcProvider }}
{{- if .Values.okta }}
- name: OKTA_DOMAIN
  value: {{ quote .Values.okta.domain }}
- name: OKTA_CLIENT_ID
  value: {{ quote .Values.okta.clientId }}
- name: OKTA_CLIENT_SECRET
  value: {{ quote .Values.okta.clientSecret }}
- name: OKTA_AUTH_SERVER_ID
  value: {{ quote .Values.okta.authorizationServerId }}
{{- end }}
{{- if .Values.b2c }}
- name: B2C_CLIENT_ID
  value: {{ quote .Values.b2c.clientId }}
- name: B2C_CLIENT_SECRET
  value: {{ quote .Values.b2c.clientSecret }}
- name: B2C_URL
  value: {{ quote .Values.b2c.url }}
{{- end }}
- name: SITE_URL
{{- if .Values.pr }}
  value: "{{ .Values.container.siteUrl }}-{{ .Values.pr }}.{{ .Values.ingress.server }}"
{{- else }}
  value: {{ quote .Values.container.siteUrl }}
{{- end }}
ports:
- name: http
  containerPort: {{ .Values.container.port }}
  protocol: TCP
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4 }}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4 }}
{{- end -}}
