{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-payment-web.config-map") -}}
{{- define "ffc-demo-payment-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  STATIC_CACHE_TIMEOUT_IN_MILLIS: {{ quote .Values.container.staticCacheTimeoutMillis }}
  REST_CLIENT_TIMEOUT_IN_MILLIS: {{ quote .Values.container.restClientTimeoutMillis }}
  PAYMENT_SERVICE_URL: {{ quote .Values.container.paymentServiceUrl }}
  OIDC_PROVIDER: {{ quote .Values.oidcProvider }}
{{- if .Values.okta }}
  OKTA_DOMAIN: {{ quote .Values.okta.domain }}
{{- end }}
{{- if .Values.b2c }}
  B2C_URL: {{ quote .Values.b2c.url }}
{{- end }}
{{- if .Values.pr }}
  SITE_URL: "{{ .Values.container.paymentWebSiteUrl }}-{{ .Values.pr }}.{{ .Values.ingress.server }}"
{{- else }}
  SITE_URL: {{ quote .Values.container.paymentWebSiteUrl }}
{{- end }}
{{- end }}
