{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-web-service.container-secret") -}}
{{- define "ffc-demo-payment-web-service.container-secret" -}}
stringData:
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
