{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-web-service.container-secret") -}}
{{- define "ffc-demo-payment-web-service.container-secret" -}}
data:
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | b64enc | quote }}
  {{- if .Values.okta }}
  OKTA_CLIENT_SECRET: {{ .Values.okta.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.b2c }}
  B2C_CLIENT_SECRET: {{ .Values.b2c.clientSecret | b64enc | quote }}  
  {{- end }}
{{- end -}}