trigger: none

# pool:
#   vmImage: 'ubuntu-latest'

variables:
- group: aa-test-callback

stages:
  - stage: TestStage
    jobs:
      - job: TestJob
        pool: server
        timeoutInMinutes: 10
        steps:
              
          - task: AzureFunction@1
            inputs:
              # function: 'https://adopipelineasyncfuncpoc.azurewebsites.net/api/AdoCallBack'
              # function: 'https://sndadpinffa1401aa.azurewebsites.net/api/HttpTrigger1'
              # function: 'https://github.com/DEFRA/ffc-demo-payment-web/blob/aa/deployToSnd1/.azuredevops/callbackTest.yaml'
              function: 'https://adp-flux-api--g73abmc.nicebeach-ef765564.uksouth.azurecontainerapps.io/api/AdoTask'
              key: '$(callBackKey)'
              method: 'POST'
              body: |
                '{
                "serviceName": "ffc-demo-web"
                "helmReleaseName": "ffc-demo-web",
                "helmReleaseVersion": "4.32.30",
                "environment": "SND1"
                }'
              waitForCompletion: 'true'
