pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: TestStage
    jobs:
      - job: TestJob
        pool: server
        timeoutInMinutes: 10
        steps:
              
          - task: AzureFunction@1
            inputs:
              function: 'https://aatestfuncapp.azurewebsites.net/api/callBackTest'
              key: '$(callBackKey)'
              method: 'POST'
              body: '{ "Content-Type":"application/json" }'
              waitForCompletion: 'true'