trigger: none

# pool:
#   vmImage: 'ubuntu-latest'

variables:
- group: aa-test-callback

stages:
  - stage: TestStage
    jobs:
      - job: TestJob
        pool: server
        timeoutInMinutes: 10
        steps:
              
          - task: AzureFunction@1
            inputs:
              function: 'https://aatestfuncapp.azurewebsites.net/api/callBackTest'
              key: '$(callBackKey)'
              method: 'POST'
              body: |
                '{
                "Content-Type":"application/json",
                "helmReleaseName": "ffc-demo-web-infra-post-deploy",
                "helmReleaseVersion": "4.32.30"  
                }'
              waitForCompletion: 'false'
