- key: GOOGLE_TAG_MANAGER_KEY
  value: "GTM-N5QK7RL"
- key: COOKIE_PASSWORD
  value: "{{servicename}}-COOKIE-PASSWORD" 
  type: "keyvault"
- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"  